src/Entity/Genre.php
<?php

namespace App\Entity;

use App\Repository\GenreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: GenreRepository::class)]
#[ApiResource(paginationItemsPerPage: 20,
operations:[new Get(normalizationContext: ['groups' => 'genre:item']),
            new GetCollection(normalizationContext: ['groups' => 'genre:list'])])]
class Genre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 35)]
    #[Groups(['genre:list', 'genre:item'])]
    private ?string $Nomgenre = null;

    #[ORM\OneToMany(mappedBy: 'genre', targetEntity: Livre::class)]
    #[Groups(['livre:list', 'list:item', 'genre:list', 'genre:item'])]
    private Collection $livres;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomgenre(): ?string
    {
        return $this->Nomgenre;
    }

    public function setNomgenre(string $Nomgenre): static
    {
        $this->Nomgenre = $Nomgenre;

        return $this;
    }

    /**
     * @return Collection<int, Livre>
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): static
    {
        if (!$this->livres->contains($livre)) {
            $this->livres->add($livre);
            $livre->setGenre($this);
        }

        return $this;
    }

    public function removeLivre(Livre $livre): static
    {
        if ($this->livres->removeElement($livre)) {
            // set the owning side to null (unless already changed)
            if ($livre->getGenre() === $this) {
                $livre->setGenre(null);
            }
        }

        return $this;
    }

   
}

src/Controller/BaseController.php
<?php

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Ajouter;
use App\Entity\Contact;
use App\Entity\Faq;
use App\Entity\Genre;
use App\Entity\Livre;
use App\Entity\Panier;
use App\Entity\Type;
use App\Form\AjoutType;
use App\Form\ContactType;
use App\Form\FaqType;
use App\Form\GenreType;
use App\Form\TypeDeLivreType;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email; // cette ligne devient inutile
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class BaseController extends AbstractController
{
    #[Route('/index', name: 'index')]
    public function index(EntityManagerInterface $entityManagerInterface ): Response
    {
        $repoLivre = $entityManagerInterface->getRepository(Livre::class);
        $livre = $repoLivre->findAll();

        $repoGenre = $entityManagerInterface->getRepository(Genre::class);
        $genre = $repoGenre->findAll();

        return $this->render('base/index.html.twig', [
            'livre'=>$livre,
            'genre'=>$genre,    
        ]);
    }

    #[Route('/contact', name:'contact')] // étape 1
    public function contact(Request $request, MailerInterface $mailer, EntityManagerInterface $entityManagerInterface): Response
    {
        $contact = new Contact();
        $form = $this->createForm(ContactType::class, $contact);

        if($request->isMethod('POST')){
            $form->handleRequest($request);
            if ($form->isSubmitted()&&$form->isValid()){
                $email = (new TemplatedEmail())
                ->from($contact->getEmail())
                ->to('cheztristan@gmail.com')
                ->subject($contact->getSujet())
                ->htmlTemplate('emails/email.html.twig')
                ->context([
                    'nom'=> $contact->getNom(),
                    'sujet'=> $contact->getSujet(),
                    'message'=> $contact->getMessage()
                ]);
              
                $entityManagerInterface->persist($contact);
                $entityManagerInterface->flush();

                $mailer->send($email);
                $this->addFlash('notice','Message envoyé');
                return $this->redirectToRoute('contact');
               
            }
        }

        return $this->render('base/contact.html.twig', [ // étape 3
            'form' => $form->createView()
            
        ]);
    }

    #[Route('/private-ajout', name: 'ajout')]
    public function ajout(Request $request, SluggerInterface $slugger, EntityManagerInterface $entityManagerInterface): Response
    {
        $livre= new Livre();

        $form = $this->createForm(AjoutType::class,$livre);
        if($request->isMethod('POST')){
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()){
                $fichier = $form->get('Couverture')->getData();
                
                if($fichier){
                 $nomFichier = pathinfo($fichier->getClientOriginalName(), PATHINFO_FILENAME);
                 $nomFichier = $slugger->slug($nomFichier);
                 $nomFichier = $nomFichier.'-'.uniqid().'.'.$fichier->guessExtension();
                    try{                 
                        $fichier->move($this->getParameter('file_directory'), $nomFichier);
                        $this->addFlash('notice', 'Fichier envoyé');
                    }
                    catch(FileException $e){
                        $this->addFlash('notice', 'Erreur d\'envoi');
                    }        
                }
                $livre->setCouverture($nomFichier);
                $entityManagerInterface->persist($livre);
                $entityManagerInterface->flush();

                return $this->redirectToRoute('ajout');
            }
        }

        return $this->render('base/ajout.html.twig', [
            'form' => $form->createView()
        ]);
    } 

    #[Route('/favorie/{id}', name: 'favorie')] // étape 1
    public function favorie(Request $request, EntityManagerInterface $entityManagerInterface): Response // étape 2
    {
        $id=$request -> get('id');
        $action = $request -> get('action');
        $livre=$entityManagerInterface->getRepository(Livre::class)->find($id);

        if($action == 'ajouter'){
            $this->getUser()->addFavory($livre);
        }
        if($action == 'supprimer'){
            $this->getUser()->removeFavory($livre);
        }

        $entityManagerInterface->persist($this->getUser());
        $entityManagerInterface->flush();

        return $this->render('base/mes-favorie.html.twig', [ // étape 3
            
        ]);
    } 

    #[Route('/mes-favorie', name: 'mes-favorie')] // étape 1
    public function mesFavorie(): Response // étape 2
    {
        $user = $this->getuser();
        $favorie = $user->getFavories();

        return $this->render('base/mes-favorie.html.twig', [ // étape 3
            'favorie' => $favorie,
            
        ]);
    }

    #[Route ('/detail/{id}', name: 'detail')]
    public function detail(Request $request, EntityManagerInterface $entityManagerInterface): Response
    {
        $id=$request -> get('id');
        $livre = $entityManagerInterface ->getRepository(Livre::class)->find($id);

        if (!$livre) {
            throw $this->createNotFoundException(
                'Aucun article trouvé pour l\'id '.$id
            );
        }

        return $this->render('base/detail.html.twig', [
            'livre' => $livre,
        ]);
    }

    #[Route('/monPanier', name: 'monPanier')] // étape 1
    public function monPanier(Request $request, EntityManagerInterface $entityManagerInterface): Response // étape 2
    {
        $repoLivre = $entityManagerInterface->getRepository(Livre::class);
        $livre = $repoLivre->findAll();

        return $this->render('base/monPanier.html.twig', [ // étape 3
            'livres' => $livre,
            
        ]);
    }

    #[Route('/ajoutPanier/{id}', name:'ajoutPanier')]
    public function ajoutPanier(Request $request, EntityManagerInterface $entityManagerInterface): Response        
    {
        $id = $request->get('id');
        $user = $this->getUser();
        $panier = $user->getPanier();

        if ($panier === null) {
            $panier = new Panier();
            $user->setPanier($panier);
            $entityManagerInterface->persist($panier);
        }

        $ajouter = new Ajouter();
        $livre= $entityManagerInterface->getRepository(Livre::class)->find($id);
        if ($livre != null) {
            $ajouter -> setLivre($livre);
            $ajouter -> setPanier($panier);
            $entityManagerInterface->persist($ajouter);
        }

        $entityManagerInterface->persist($user);
        $entityManagerInterface->flush();

        return $this->redirectToRoute('index');
            
    }

    #[Route('/supprimerPanier/{id}', name: 'supp-panier')]
    public function supprimerPanier($id, EntityManagerInterface $entityManagerInterface): Response
    {
        $ajouter = $entityManagerInterface->getRepository(Ajouter::class)->find($id);

        if ($ajouter) {
            $entityManagerInterface->remove($ajouter);
            $entityManagerInterface->flush();
        }

        return $this->redirectToRoute('monPanier');
    }

    #[Route('/faq', name: 'faq')]
    public function faq(Request $request, EntityManagerInterface $emi): Response
    {
        $repoFaq = $emi->getRepository(Faq::class);
        
        $faq = $repoFaq->findAll();
    
        $form = $this->createForm(FaqType::class);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            if ($this->isGranted('ROLE_ADMIN')) {
                // Récupérer la réponse à partir du formulaire
                $reponse = $form->get('reponse')->getData();
                // Parcourir chaque question faq et définir la réponse
                foreach ($faq as $faqItem) {
                    // Vérifier si la question n'a pas déjà de réponse
                    if ($faqItem->getReponse() === null) {
                        $faqItem->setReponse($reponse);
                    }
                }
                $emi->flush();
            }
            return $this->redirectToRoute('faq');
        }
    
        return $this->render('base/faq.html.twig', [
            'form' => $form->createView(),
            'faq' => $faq,
        ]);
    }
    

    #[Route('/faq/modifier/{id}', name: 'modifierFaq')]
    public function modifierFaq(Request $request, EntityManagerInterface $emi): Response
    {
        $faq = $emi->getRepository(Faq::class)->find($id);

        $modifForm = $this->createForm(ModifFaqType::class, $faq);  
        $modifForm->handleRequest($request);
        if ($modifForm->isSubmitted() && $modifForm->isValid()) {
            $emi->flush();
            $this->addFlash('notice', 'Réponse modifiée avec succès');
            return $this->redirectToRoute('faq');
        }

        return $this->render('base/modifFaq.html.twig', [
            'modifForm' => $modifForm->createView(), // 1
            'modif' => $faq, // 2
        ]);
    }

    #[Route('/mentionslegales', name: 'mentionslegales')] // étape 1
    public function mentionslegales(): Response // étape 2
    {
        return $this->render('base/mentionslegales.html.twig', [ // étape 3
            
        ]);
    }

    #[Route('/cgu', name: 'cgu')] // étape 1
    public function cgu(): Response // étape 2
    {
        return $this->render('base/cgu.html.twig', [ // étape 3
            
        ]);
    }

templates/base/ajout.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout
{% endblock %}

{% block body %}
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-10 titre">
				<h1 class="text-center titre mt-4 pt-4 display-1 fw-bold">
					Ajout</h1>
				{{form(form)}}
			</div>
		</div>
	</div>

	{% endblock %}

templates/base/cgu.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}} Conditions générales d'utilisation{% endblock %}

{% block body %}
<h1 class="text-center mt-4 pt-4 display-1 fw-bold titre"> Conditions générales d'utilisation </h1>

<div class="w-75 ms-5 mt-5">
    <p>
        Bienvenue sur le site internet de Minerva. En accedant à notre site vous acceptez les présentes conditions
        générales d'utilisation.
        Veuillez les lire attentivement avant d'utiliser notre site.
    </p>

    <ol>
        <li>
            <h4> Propriété intellectuelle </h4>
            <p> Le contenu sur notre site internet, y compris les textes, images, logos, marques de commerce et
                graphismes
                est protégé par des droits de propriété intellectuelle. Vous ne pouvez pas reproduire, distribuer,
                modifier
                ou exploiter ce contenu sans notre autorisation écrite.
            </p>
        </li>
        <li>
            <h4> Utilisation du site </h4>
            <p> Vous pouvez utiliser notre site pour naviguer, passer des commandes en ligne et vous abonner à notre
                newsletter.
                Vous ne pouvez pas utiliser notre site à des fins illégales, frauduleuses ou nuisibles.
            </p>
        </li>
        <li>
            <h4> Confidentialité </h4>
            <p> Minerva s'engage à protéger vos données personnelles conformmément à notre charte de protection des
                données
                personnelles. Veuillez lire notre charte pour en savoir plus sur la manière dont nous collectons,
                utilisons et stockons
                vos données personnelles.
            </p>
        </li>
        <li>
            <h4> Liens vers d'autre sites </h4>
            <p> Notre site peut contenir des liens vers des sites tiers. Nous ne sommes pas responsables du contenu
                ou des pratiques de ces sites. L'utilisation de ces sites est à vos risques et périls.
            </p>
        </li>
        <li>
            <h4> Responsabilité </h4>
            <p> Nous nous efforçons de maintenir notre site à jour et fonctionnel. Cependant, nous ne pouvons pas
                garantir
                que notre site sera toujours accessible et exempt d'erreur ou de virus. Minerva n'est pas reponsable des
                dommages
                directs ou indirects résultant de l'utilisation de notre site.
            </p>
        </li>
        <li>
            <h4> Commande en ligne </h4>
            <p> Vous pouvez passer des commandes en ligne sur notre site internet. Toutes les commandes sont sujettes à
                notre
                confirmation et la disponibilité des produits. Minerva se réserve le droit de refuser toutes commandes
                pour quelque
                raison que ce soit
            </p>
        </li>
        <li>
            <h4> Prix et paiement </h4>
            <p> Les prix des produits affichés sur notre site sont en euros et incluent la TVA. Les frais de livraison
                ne sont pas inclus
                dans les prix affichés. Les paiements doivent être effectués en euros. Nous acceptons les paiements par
                carte de crédit,
                carte de débit et PayPal.
            </p>
        </li>
        <li>
            <h4> Livraison </h4>
            <p> Minerva s'engage à expédier vos commandes dans les plus brefs délais. Les délais de livraison dépendent
                de votre
                adresse de livraison et de la disponibilité des produits. Nous ne sommes pas responsable des retards de
                livraison causés
                par des évènements indépendants de notre volonté.
            </p>
        </li>
        <li>
            <h4> Concernant votre âme </h4>
            <p> Lorsque vous acceptez ces conditions générales d'utilisation vous vous engagez également à donner votre
                âme
                en tribut à Belzebuth. Rien de ce que vous ne pourrez dire par la suite n'y changera quoi que ce soit.
            </p>
        </li>
        <li>
            <h4> Droits applicables et juridiction compétente </h4>
            <p> Les présentes conditions générales d'utilisation sont régies par les lois françaises Tout litige
                découlant
                de l'utilisation de notre site internet sera soumis à la juridiction des tribunaux français.
            </p>
        </li>
        <li>
            <h4> Modification des conditions générales d'utilisation </h4>
            <p> Nous nous réservons le droit de modifier ces conditions générales d'utilisation à tout moment. Les
                modifications
                prendront effet dès leur publication sur notre site internet.
            </p>
        </li>
    </ol>

    <p class="mb-5"> Si vous avez des questions ou des préoccupations concernant nos conditions générales d'utilisation,
        veuillez
        nous contacter via notre formulaire de contact.
    </p>
</div>
{% endblock %}

templates/base/charte.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}}Charte de protection des données personnelles{% endblock %}

{% block body %}
<h1 class="text-center mt-4 pt-4 display-1 fw-bold titre"> Charte de protection des données personnelles </h1>

<div class="w-75 ms-5 my-5 ">
    <p>
        Minerva s'engage à protéger vos données personnelles et à protéger votre vie privée.
        Cette charte décrit la manière dont nous collectons, utilisons, stockons et protégeons vos données personnelles
        lorsque vous utilisez notre site internet.
    </p>

    <ol>
        <li>
            <h4> Collecte et utilisation de données personnelles </h4>
            <p> Nous collectons des informations personnelles que lorsque vous créez un compte,
                effectuez une commande en ligne ou nous contactez via notre formulaire de contact. Les informations
                collectées
                peuvent inclure votre nom, votre adresse e-mail, votre adresse postale, votre numéro de téléphone et vos
                préférences bancaires.
            </p>
        </li>
    </ol>
    <p> Nous utilisons ces informations afin de traiter vote commande ou répondre à vos questions. Nous pouvons
        également
        utiliser vos informations pour vous informer des évènements à venir, des offres promotionnelles ou des nouvelles
        arrivées de notre librairie.
    </p>

    <ol start="2">
        <li>
            <h4> Stockage et protection des données personnelles</h4>
            <p> Vos données personnelles sont stockées sur des serveurs sécurisés et des mesures techniques et
                organisationnelles appropriées sont
                continuellement prises afin de protéger vos données contre la perte, l'utilisation abusive, l'accès non
                autorisé ou la divulagtion.
            </p>
        </li>
    </ol>
    <p> Nous ne transmettons pas vos données personnelles à des tiers dans la mesure du nécessaire afin de traiter votre
        commande
        ou si nous sommes tenus de le faire par la loi.
    </p>

    <ol start="3">
        <li>
            <h4> Droits des utilisateurs</h4>
            <p> Vous avez le droit d'accéder à vos données personnelles, de les rectifier et de les supprimer ou de
                limiter
                leur traitement. Vous pouvez également vous opposer au traitement de vos données personnelles à des fins
                de marketing
                direct. Pour exercer ces droits veuillez nous contacter via notre formulaire de contact.
            </p>
        </li>
        <li>
            <h4> Cookies </h4>
            <p>Nous utilisons des cookies sur notre site internet pour améliorer votre expérience utilisateur et pour
                collecter
                des données statistiques sur l'utilisation de notre site. Les cookies sont de petits fichiers stockés
                sur votre ordinateur
                ou votre appareil mobile lorsque vous visitez notre site. Vous pouvez à tout moment désactiver les
                cookies dans les
                paramètres de votre navigateur.
            </p>
        </li>
        <li>
            <h4>Modification de la charte</h4>
            <p>Nous nous réservons le droit de modifier cette charte à tout moment. Les modificationsprendront effet dès
                leurs publications sur notre site internet.
            </p>
        </li>
    </ol>

    <p> Si vous avez des questions concernant notre charte de protection des données personnelles,
        n'hésitez pas à nous contacter via notre formulaire de contact.
    </p>

</div>

{% endblock %}

templates/base/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}}Nous contacter{% endblock %}

{% block body %}
    
    <div class="container-fluid">
	    <div class="row justify-content-center">
			
                    <div class="col-10 titre">
                        <h1 class="text-center mt-4 pt-4 display-1 fw-bold titre"> Nous Contacter </h1>
                        {{form(form)}}
                    </div>    
	    </div>
	</div>
{% endblock %}

templates/base/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{parent()}}Détails
{% endblock %}

{% block body %}

	<div class="container my-5 bordure">
		<div class="row text-center">
			<div class="col-md-4 col-12">
				<img src="{{ asset('image/couverture/' ~ livre.couverture) }}" alt="{{ livre.couverture }}" class="img-fluid rounded-start" style="max-width: 300px">
			</div>
			<div class="col-md-7 col-12 text-md-start text-center mt-3">
				<div class="row">
					<div class="col">
						<h2 class="card-title">{{ livre.titre }}</h2>
					</div>
				</div>
				<div class="row">
					<div class="col">
						<div class="row mt-5">
							<div class="col">
								<span class="material-symbols-outlined det">
									apartment
								</span>
								{{ livre.editeur }}
							</div>
						</div>
						<div class="row mt-3">
							<div class="col">
								<span class="material-symbols-outlined det">
									fit_page
								</span>
								{{ livre.format }}
							</div>
						</div>
						<div class="row mt-3 mb-5">
							<div class="col">
								<span class="material-symbols-outlined det">
									language
								</span>
								{{ livre.langue }}
							</div>
						</div>
					</div>
					<div class="col">
						<div class="row mt-5">
							<div class="col">
								<span class="material-symbols-outlined det">
									payments
								</span>
								{{livre.prix|number_format(2)}}
								€
							</div>
						</div>
						<div class="row mt-3">
							<div class="col">
								<span class="material-symbols-outlined det">
									auto_stories
								</span>
								{{ livre.type.nomType }}
							</div>
						</div>
						<div class="row mt-3 mb-5">
							<div class="col">
								<span class="material-symbols-outlined det">
									format_ink_highlighter
								</span>
								{{ livre.genre.nomGenre }}
							</div>
						</div>
					</div>
				</div>
				<div class="row mt-5">
					<div class="col">
						{{ livre.resume }}
					</div>
				</div>
			</div>
		</div>
	</div>


{% endblock %}

templates/base/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{parent()}}Accueil
{% endblock %}

{% block body %}

	<div class="carrousel-container my-5">
		<span class="material-symbols-outlined arrow left-arrow" id="btavant">
			navigate_before
		</span>
		<ul id="carrousel">
			<li class="carou">
				<img src="image/festiparis.jpg" class="d-block w-100" alt="paris">
			</li>
			<li class="carou">
				<img src="image/bdangouleme.jpeg" class="d-block w-100" alt="bdangoueleme">
			</li>
			<li class="carou">
				<img src="image/saintmalo.jpeg" class="d-block w-100" alt="saintmalo">
			</li>
			<li class="carou">
				<img src="image/salonlivre.jpeg" class="d-block w-100" alt="salonlivre">
			</li>
		</ul>
		<span class="material-symbols-outlined arrow right-arrow" id="btafter">
			navigate_next
		</span>
	</div>

	<div class="genres-filter text-center my-5">
		<h3>
			Filtrer par genres
		</h3>
		<div class="form-check form-check-inline">
			<input class="form-check-input genre-checkbox" type="checkbox" id="aventure">
			<label class="form-check-label">
				Aventure
			</label>
		</div>
		<div class="form-check form-check-inline">
			<input class="form-check-input genre-checkbox" type="checkbox" id="science-fiction">
			<label class="form-check-label">
				Science Fiction
			</label>
		</div>
		<div class="form-check form-check-inline">
			<input class="form-check-input genre-checkbox" type="checkbox" id="fantasy">
			<label class="form-check-label">
				Fantasy
			</label>
		</div>
		<div class="form-check form-check-inline">
			<input class="form-check-input genre-checkbox" type="checkbox" id="post-apocalyptique">
			<label class="form-check-label">
				Post Apocalyptique
			</label>
		</div>
		<div class="form-check form-check-inline">
			<input class="form-check-input genre-checkbox" type="checkbox" id="humoristique">
			<label class="form-check-label">
				Humoristique
			</label>
		</div>
	</div>


	<div class="d-flex flex-wrap justify-content-center">
		{% for l in livre %}
			<div class="card m-2 livre-card" style="max-width: 540px;">
				<div class="row g-0">
					<div class="col-md-4">
						<img src="image/couverture/{{l.couverture}}" alt={{l.couverture}} class="img-fluid rounded-start">
						<p class="card-text mt-4 ms-2">
							<small class="text-muted">{{l.editeur}}</small>
						</p>
						{#<p class="card-text ms-2">
													<small class="text-muted">{{l.format}}</small>
												</p>#}
						<p class="card-text ms-2">
							<strong>{{l.prix|number_format(2)}}
								<sup>€</sup>
							</strong>
						</p>
						<p class="card-text ms-2 test">
							<strong id="{{l.genre.nomgenre}}" class="hidden">{{ l.genre.nomgenre }}
							</strong>
						</p>
					</div>
					<div class="col-md-8">
						<div class="card-body">
							<h4 class="card-title">{{l.titre}}</h4>
							<p class="card-text mt-3">{{l.auteur}}</p>
							<p class="card-text mt-4 overflow-auto" style="height: 282px">{{l.resume}}</p>
						</div>
					</div>
				</div>
				<div class="card-footer">
					{% if is_granted ('IS_AUTHENTICATED_FULLY') %}
						{% if app.user %}
							{#{% if l in app.user.favories %}
															<a href="{{path('favorie', {'id': l.id, 'action': 'supprimer'}) }}" class="btn btn-secondary">
																<span class="material-symbols-outlined">
																	bookmark_added
																</span>
															</a>
														{% else %}
															<a href="{{path('favorie', {'id': l.id, 'action': 'ajouter'}) }}" class="btn btn-secondary">
																<span class="material-symbols-outlined">
																	bookmark_add
																</span>
															</a>
														{% endif %}#}
							{% else %}
							{#<button class="btn btn-secondary">
															<span class="material-symbols-outlined">
																bookmark
															</span>
														</button>#}
						{% endif %}
						<a href="{{path('detail', {'id': l.id}) }}" class="btn btn-secondary">
							<span class="material-symbols-outlined">
								open_in_new
							</span>
						</a>
						<a href="{{path('ajoutPanier', {'id': l.id}) }}" class="btn btn-secondary">
							<span>
								ACHETER
							</span>
						</a>
					{% endif %}
					{% if not is_granted ('IS_AUTHENTICATED_FULLY') %}
						{#<a href="{{path('app_login', {'id': l.id}) }}" class="btn btn-secondary">
													<span class="material-symbols-outlined">
														bookmark
													</span>
												</a>#}
						<a href="{{path('detail', {'id': l.id}) }}" class="btn btn-secondary">
							<span class="material-symbols-outlined">
								open_in_new
							</span>
						</a>
						<a href="{{path('app_login', {'id': l.id}) }}" class="btn btn-secondary">
							<span>
								ACHETER
							</span>
						</a>
					{% endif %}
				</div>
			</div>
		{% endfor %}
	</div>


{% endblock %}

templates/base/modifFaq.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réponse FAQ
{% endblock %}

{% block body %}
<h1 class="text-center pt-4 display-2 fw-bold"> REPONSE FAQ </h1>

<div class="container-fluid">
<div class="card mx-auto" style="width: 20rem;">
    <div class="card-body">
      <h5 class="card-title">Modifier la réponse</h5>
      <p class="card-text">{{form(modifForm)}}</p>
    </div>
  </div>
</div>

{% endblock %}